on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
name: Swift Unit Tests
jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
      matrix:
        destination:
          - "platform=iOS Simulator,OS=12.2,name=iPhone X"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install NPM modules
        run: |
          npm list --depth=0
          npm install
          npm list --depth=0
      - name: Install Cocoapods
        run: |
          cd ios
          pod install
      - name: Build and test
        run: |
          cd ios
          xcodebuild clean test -workspace Plugin.xcworkspace -scheme Plugin -destination "${destination}"
          bash <(curl -s https://codecov.io/bash)
        env:
          destination: ${{ matrix.destination }}
